### DISCUSSION TITLE
V8のrust bindingをライブラリとして使ってみる

### DISCUSSION THREAD

**Discussion by ubugeeei** [Ubugeeei/work-log#61] [Scraps]
# 想定環境
- macOS
- rust (v1.69.x)
- VSCode

rusty_v8
https://github.com/denoland/rusty_v8
https://docs.rs/v8/0.73.0/v8/

## 環境構築
rust, cargoのセットアップができていない場合は先にこちらを
https://www.rust-lang.org/learn/get-started

VSCodeにrust-analyzerを入れよう。
https://marketplace.visualstudio.com/items?itemName=rust-lang.rust-analyzer

# Rust (cargo) オンボーディング

## PJを作る

cargoでサクッと

```sh
cargo new v8_sanmple
cd v8_sanmple
```

## 試しに動かしてみる

cargoでサクッと

```sh
cargo run
```
"Hello, world"が出力されたらOK

## 簡単なディレクトリの説明
- src/main.rs  
   rustのソースコード。モジュールを作る際はsrcに作っていく。今回はmain.rsだけ使っておけばOK.
- target  
  ビルドしたりすると成果物がここに生成される。触ることないので気にしなくてOK
- Cargo.toml  
  package.jsonみたいなもん。必要なパッケージとかがあればdependenciesを追加したいりする。
- Cargo.lock  
  ロックファイル。触らないので気にしなくてOK

# 簡単にrusty_v8を使う
## dependenciesにrusty_v8を追加する
Cargo.toml  をいじる
```toml
[package]
name = "simple_use"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
v8 = "0.73.0" # ここ
```

後は使いたいところでuseするだけ。
試しにmain.rsでuseしてみる。

```rs
use v8;

fn main() {
    println!("Hello, world!");
}
```

宣言しただけで、特に何もしてないが、試しに動かしてみるとインストールが始まると思う(時間かかる)

```sh
cargo run
```

---

軽くスクラップを書くつもりがなんと手元のPCでビルドができない事態に。
また気が向いたら書く
